"""Database seeding.

`ensure_catalogue` is idempotent and runs on every startup so the exercise
catalogue always matches app/catalogue.py.

`seed_demo` builds the demo clinic used for walkthroughs. Historical sessions
are generated by simulating plausible per-repetition angle measurements and
then running them through the *real* movement-quality layer, so every number
on the dashboard comes from the same code path a live session uses.
"""

from __future__ import annotations

import random
from datetime import date, datetime, time, timedelta, timezone

from sqlalchemy import select
from sqlalchemy.orm import Session

from .catalogue import EXERCISES
from .database import Base, SessionLocal, engine
from .models import (
    Exercise,
    ExerciseSession,
    PatientProfile,
    PhysiotherapistProfile,
    PlanStatus,
    PrescribedExercise,
    ProgressMetric,
    RehabilitationPlan,
    SessionRep,
    SessionStatus,
    User,
    UserRole,
)
from .security import hash_password
from .services import quality

DEMO_PASSWORD = "physio123"


def ensure_catalogue(db: Session) -> None:
    """Insert or update catalogue exercises. Safe to call repeatedly."""
    by_slug = {e.slug: e for e in db.scalars(select(Exercise))}
    for spec in EXERCISES:
        exercise = by_slug.get(spec["slug"])
        if exercise is None:
            db.add(Exercise(**spec))
        else:
            for key, value in spec.items():
                setattr(exercise, key, value)
    db.commit()


def _make_user(db: Session, name: str, email: str, role: UserRole) -> User:
    user = User(
        name=name,
        email=email,
        password_hash=hash_password(DEMO_PASSWORD),
        role=role,
    )
    db.add(user)
    db.flush()
    return user


def _simulate_reps(
    count: int, peak: float, consistency: float, rng: random.Random
) -> list[quality.RepFeatures]:
    """Plausible per-repetition measurements around a target peak angle."""
    reps = []
    for i in range(count):
        jitter = rng.gauss(0, (1 - consistency) * 9)
        max_angle = max(10.0, min(150.0, peak + jitter))
        min_angle = max(0.0, rng.gauss(6, 3))
        duration = max(0.6, rng.gauss(3.2, 0.9 * (1.4 - consistency)))
        reps.append(
            quality.RepFeatures(
                index=i,
                min_angle=round(min_angle, 1),
                max_angle=round(max_angle, 1),
                duration_seconds=round(duration, 2),
                peak_velocity=round(abs(rng.gauss(45, 10)), 1),
                mean_visibility=round(min(1.0, max(0.3, rng.gauss(0.88, 0.07))), 2),
            )
        )
    return reps


def _record_session(
    db: Session,
    patient: PatientProfile,
    pe: PrescribedExercise,
    when: datetime,
    reps_attempted: int,
    peak: float,
    consistency: float,
    rng: random.Random,
) -> None:
    target = pe.target_rom or pe.exercise.default_target_rom
    tracked = pe.exercise.cv_supported
    features = _simulate_reps(reps_attempted, peak, consistency, rng) if tracked else []
    assessment = quality.assess_session(features, target)

    session = ExerciseSession(
        patient_id=patient.id,
        prescribed_exercise_id=pe.id,
        started_at=when - timedelta(minutes=4),
        completed_at=when,
        status=SessionStatus.completed,
        reps_prescribed=pe.repetitions,
        reps_attempted=reps_attempted,
        tracking_mode="camera" if tracked else "self_reported",
        pose_coverage=round(rng.uniform(0.86, 0.99), 2) if tracked else None,
    )
    if tracked:
        session.reps_valid = assessment.reps_valid
        session.quality_score = assessment.quality_score
        session.rom_max = assessment.rom_max
        session.rom_mean = assessment.rom_mean
    session.feedback = " ".join(
        quality.patient_feedback(assessment, reps_attempted, pe.repetitions)
    )
    db.add(session)
    db.flush()

    for feature, verdict in zip(features, assessment.assessments):
        db.add(
            SessionRep(
                session_id=session.id,
                index=feature.index,
                min_angle=feature.min_angle,
                max_angle=feature.max_angle,
                rom=round(feature.excursion, 1),
                duration_seconds=feature.duration_seconds,
                peak_velocity=feature.peak_velocity,
                mean_visibility=feature.mean_visibility,
                valid=verdict.valid,
                classification=verdict.classification,
                reason=verdict.reason,
            )
        )

    if session.rom_max is not None:
        db.add(
            ProgressMetric(
                patient_id=patient.id,
                exercise_id=pe.exercise_id,
                session_id=session.id,
                metric_type="rom_max",
                value=session.rom_max,
                recorded_at=when,
            )
        )


def _build_plan(
    db: Session,
    patient: PatientProfile,
    therapist: PhysiotherapistProfile,
    title: str,
    condition: str,
    start_offset_days: int,
    items: list[dict],
    catalogue: dict[str, Exercise],
) -> RehabilitationPlan:
    today = datetime.now(timezone.utc).date()
    plan = RehabilitationPlan(
        patient_id=patient.id,
        therapist_id=therapist.id,
        title=title,
        condition=condition,
        start_date=today - timedelta(days=start_offset_days),
        end_date=today + timedelta(days=28 - start_offset_days),
        status=PlanStatus.active,
    )
    db.add(plan)
    db.flush()
    for order, item in enumerate(items):
        db.add(
            PrescribedExercise(
                plan_id=plan.id,
                exercise_id=catalogue[item["slug"]].id,
                sets=item["sets"],
                repetitions=item["reps"],
                frequency_per_day=item.get("frequency", 1),
                instructions=item.get("instructions", ""),
                target_rom=item.get("target_rom"),
                order_index=order,
            )
        )
    db.flush()
    db.refresh(plan)
    return plan


def seed_demo(db: Session, *, reset: bool = False) -> None:
    """Create the demo clinic. No-op if it already exists unless reset=True."""
    if reset:
        Base.metadata.drop_all(bind=engine)
        Base.metadata.create_all(bind=engine)

    ensure_catalogue(db)
    catalogue = {e.slug: e for e in db.scalars(select(Exercise))}

    if db.scalar(select(User).where(User.email == "ananya.rao@physiopilot.demo")):
        return

    rng = random.Random(20240607)
    today = datetime.now(timezone.utc).date()

    therapist_user = _make_user(
        db, "Dr. Ananya Rao", "ananya.rao@physiopilot.demo", UserRole.physiotherapist
    )
    therapist = PhysiotherapistProfile(
        user_id=therapist_user.id,
        clinic_name="Chennai Rehab Clinic",
        registration_number="TN-PT-40118",
    )
    db.add(therapist)
    db.flush()

    def add_patient(name: str, email: str, dob: date, phone: str) -> PatientProfile:
        user = _make_user(db, name, email, UserRole.patient)
        profile = PatientProfile(
            user_id=user.id,
            assigned_therapist_id=therapist.id,
            date_of_birth=dob,
            phone=phone,
            language="en",
        )
        db.add(profile)
        db.flush()
        return profile

    # -- Rahul: adhering well, observed range improving ----------------------
    rahul = add_patient(
        "Rahul Kumar", "rahul.kumar@physiopilot.demo", date(1968, 4, 12), "+91 98400 11223"
    )
    rahul.notes = "Right total knee replacement on 12 May. Lives with family, uses a walker indoors."
    rahul_plan = _build_plan(
        db, rahul, therapist, "Week 3 - Post-operative knee", "Post-operative knee rehabilitation", 20,
        [
            {
                "slug": "heel_slide", "sets": 3, "reps": 10, "frequency": 2, "target_rom": 75,
                "instructions": "Lie on your back. Slide your heel slowly towards you, hold for two seconds, then slide back.",
            },
            {
                "slug": "straight_leg_raise", "sets": 3, "reps": 10, "frequency": 1, "target_rom": 45,
                "instructions": "Keep the knee straight and lift the leg about 30 cm. Lower slowly.",
            },
            {
                "slug": "knee_flexion", "sets": 2, "reps": 10, "frequency": 1, "target_rom": 95,
                "instructions": "Sit on a chair. Bend the knee back under the chair as far as is comfortable.",
            },
        ],
        catalogue,
    )

    # -- Priya: adherence slipping, range not progressing --------------------
    priya = add_patient(
        "Priya Sharma", "priya.sharma@physiopilot.demo", date(1975, 9, 3), "+91 98410 55871"
    )
    priya.notes = "Conservative management of patellofemoral pain. Reports difficulty finding time in the evening."
    priya_plan = _build_plan(
        db, priya, therapist, "Week 2 - Knee rehabilitation", "Knee rehabilitation (non-surgical)", 13,
        [
            {
                "slug": "knee_flexion", "sets": 3, "reps": 10, "frequency": 1, "target_rom": 100,
                "instructions": "Sit tall and bend the knee slowly. Stop if it is painful.",
            },
            {
                "slug": "sit_to_stand", "sets": 2, "reps": 10, "frequency": 1,
                "instructions": "Use a firm chair. Stand without using your hands if you can.",
            },
        ],
        catalogue,
    )

    # -- Suresh: just started, little history yet ----------------------------
    suresh = add_patient(
        "Suresh Menon", "suresh.menon@physiopilot.demo", date(1957, 1, 22), "+91 98420 30947"
    )
    suresh.notes = "Left knee arthroscopy on 2 June. Retired teacher, motivated, low phone familiarity."
    suresh_plan = _build_plan(
        db, suresh, therapist, "Week 1 - Early knee mobility", "Post-arthroscopy knee rehabilitation", 5,
        [
            {
                "slug": "heel_slide", "sets": 2, "reps": 10, "frequency": 1, "target_rom": 60,
                "instructions": "Move gently. Stop before pain and let the knee rest between repetitions.",
            },
            {
                "slug": "straight_leg_raise", "sets": 2, "reps": 8, "frequency": 1, "target_rom": 35,
                "instructions": "Tighten the thigh first, then lift the whole leg together.",
            },
        ],
        catalogue,
    )

    def history(
        patient: PatientProfile,
        plan: RehabilitationPlan,
        days: int,
        completion_rate: float,
        start_peak: dict[str, float],
        daily_gain: dict[str, float],
        consistency: float,
        skip_today: bool = False,
        seed: int = 0,
    ) -> None:
        """Generate past sessions.

        `skip_today` leaves the current day empty so that patient opens the app
        with their routine still to do. Without it the walkthrough patient sees
        a "finished for today" screen and there is no START button to press.
        """
        # Each patient draws from their own stream, so tuning one patient's
        # story does not silently change everybody else's numbers.
        rng = random.Random(seed)

        for day_offset in range(days, 0, -1):
            day = today - timedelta(days=day_offset - 1)
            if day < plan.start_date:
                continue
            if skip_today and day == today:
                continue
            for pe in plan.prescribed_exercises:
                for occurrence in range(pe.frequency_per_day):
                    if rng.random() > completion_rate:
                        continue
                    slug = pe.exercise.slug
                    elapsed = (day - plan.start_date).days
                    peak = start_peak.get(slug, 60) + daily_gain.get(slug, 0) * elapsed
                    peak += rng.gauss(0, 1.5)
                    when = datetime.combine(day, time(hour=8 + occurrence * 7, minute=rng.randint(0, 50)))
                    reps = pe.repetitions - (1 if rng.random() < 0.15 else 0)
                    _record_session(db, patient, pe, when, reps, peak, consistency, rng)

    history(
        rahul, rahul_plan, days=21, completion_rate=0.88,
        start_peak={"heel_slide": 62, "straight_leg_raise": 34, "knee_flexion": 71},
        daily_gain={"heel_slide": 0.85, "straight_leg_raise": 0.55, "knee_flexion": 1.15},
        consistency=0.70,
        # Rahul is the walkthrough patient: today must still be open for him.
        skip_today=True,
        seed=101,
    )
    history(
        priya, priya_plan, days=14, completion_rate=0.5,
        start_peak={"knee_flexion": 96, "sit_to_stand": 0},
        daily_gain={"knee_flexion": -1.1},
        consistency=0.5,
        seed=202,
    )
    history(
        suresh, suresh_plan, days=6, completion_rate=0.8,
        start_peak={"heel_slide": 48, "straight_leg_raise": 26},
        daily_gain={"heel_slide": 1.4, "straight_leg_raise": 0.9},
        consistency=0.62,
        skip_today=True,
        seed=303,
    )

    db.commit()


def main() -> None:
    import argparse

    parser = argparse.ArgumentParser(description="Seed the PhysioPilot database")
    parser.add_argument(
        "--reset", action="store_true", help="Drop and recreate all tables first"
    )
    args = parser.parse_args()

    Base.metadata.create_all(bind=engine)
    with SessionLocal() as db:
        seed_demo(db, reset=args.reset)
    print("Seeded demo clinic.")
    print(f"  Physiotherapist: ananya.rao@physiopilot.demo / {DEMO_PASSWORD}")
    print(f"  Patient:         rahul.kumar@physiopilot.demo / {DEMO_PASSWORD}")


if __name__ == "__main__":
    main()
